# Generated by Django 5.1.6 on 2025-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pledgedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(max_length=254)),
                ('book_title', models.CharField(max_length=200)),
                ('book_type', models.CharField(choices=[('curriculum', 'Curriculum'), ('storybook', 'Storybook'), ('general', 'General Reading')], max_length=50)),
                ('delivery_option', models.CharField(max_length=200)),
                ('book_image', models.ImageField(upload_to='book_donations/')),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
