# Generated by Django 5.1.6 on 2025-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookexchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookexchange',
            old_name='email_or_phone',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='bookexchange',
            old_name='payment_status',
            new_name='delivery_paid',
        ),
        migrations.RenameField(
            model_name='bookexchange',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bookexchange',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='bookexchange',
            name='date_added',
        ),
        migrations.AddField(
            model_name='bookexchange',
            name='file',
            field=models.FileField(default='', upload_to='book_exchange/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookexchange',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='delivery_option',
            field=models.CharField(choices=[('dropoff', 'Drop off location'), ('pickup', 'Personal pick up')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookexchange',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('science', 'Science'), ('history', 'History'), ('romance', 'Romance'), ('selfhelp', 'Self Help'), ('biography', 'Biography')], max_length=50),
        ),
    ]
