# Generated by Django 5.1.6 on 2025-03-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookExchange',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='drop_off_location',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='contact_details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='delivery_option',
            field=models.CharField(choices=[('Drop Off', 'Drop Off Location'), ('Pick Up', 'Personal Pick Up')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='donor_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Technology', 'Technology'), ('History', 'History'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('Other', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
