# Generated by Django 5.1.6 on 2025-03-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_downloadedpdf_exchangedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangedbook',
            old_name='exchanged_on',
            new_name='exchange_date',
        ),
    ]
