# Generated by Django 5.1.6 on 2025-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_blog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
