# Generated by Django 5.1.6 on 2025-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_booktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktransaction',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booktransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='downloadedpdf',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exchangedbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='', upload_to='cover_photos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='delivery_option',
            field=models.CharField(choices=[('Drop-off', 'Drop-off'), ('Pick-up', 'Pick-up')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='donor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Science', 'Science')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FeaturedBook',
        ),
        migrations.DeleteModel(
            name='BookTransaction',
        ),
        migrations.DeleteModel(
            name='DownloadedPDF',
        ),
        migrations.DeleteModel(
            name='ExchangedBook',
        ),
    ]
