# Generated by Django 5.1.6 on 2025-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_book_contact_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='contact_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='', upload_to='book_covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='delivery_options',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(default='', upload_to='book_documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='donor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='exchange_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
