# Generated by Django 5.1.6 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_book_contact_email_alter_book_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('science_fiction', 'Science Fiction'), ('romance', 'Romance'), ('self_help', 'Self Help'), ('history', 'History'), ('other', 'Other')], max_length=50),
        ),
    ]
