# Generated by Django 5.1.6 on 2025-03-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_location',
            new_name='location',
        ),
    ]
